[tool.poetry]
name = "elastory"
version = "0.1.0"
description = "Tools for studying long ranged —allosteric— effects in elastic networks (e.g. of proteins) on a mechanical basis."
authors = ["Maximilian Alexander Vossel <mvossel@pm.me>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/maxvossel/elastory"
homepage = "https://github.com/maxvossel/elastory"
keywords = ["physics", "biophysics", "allostery", "elastic networks", "proteins", "computational biology"]

[tool.poetry.dependencies]
python = "^3.11"
biopython = "^1.85"
dcor = "^0.6"
fastdtw = "^0.3.4"
h5py = "^3.13.0"
ipykernel = "^6.29.2"
ipywidgets = "^8.1.7"
jupyterthemes = "^0.20.0"
kaleido = "0.2.1"
matplotlib = "^3.10.3"
networkx = "^3.4.2"
numba = "^0.61.2"
numpy = "^2.2.6"
pandas = "^2.0.3"
parmap = "^1.7.0"
pillow = "^11.2.1"
plotly = "^6.1.0"
pre-commit = "^4.2.0"
pydantic = "^2.11.5"

rmsd = "^1.6.4"
ruff = "^0.11.11"
scikit-learn = "^1.6.1"
scipy = "^1.15.3"
seaborn = "^0.13.2"
tables = "^3.10.2"
tqdm = "^4.67.1"
widgetsnbextension = "^4.0.14"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
